name: Ultimate APK Protector (Docker)

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pull Obfuscapk Docker Image
        run: |
          # د ډاکر بشپړ او تیار شوی ماشین ډاونلوډ کوو
          docker pull claudiugeorgiu/obfuscapk

      - name: Run Strong Obfuscation
        run: |
          # دلته خپل اپلیکیشن (KeyStore.apk) ډاکر ماشین ته ورکوو ترڅو په یوه کلیک یې قلف کړي
          docker run --rm -v "${PWD}:/workdir" claudiugeorgiu/obfuscapk -o StringEncryption -o ClassRename -o MethodRename -o FieldRename -o CallIndirection -o ControlFlowObfuscation KeyStore.apk

      - name: Upload Protected APK
        uses: actions/upload-artifact@v4
        with:
          name: Strongly-Protected-APK
          path: KeyStore_obfuscated.apk
